IF
	True()
THEN
	RESPONSE #100
		CutSceneId("J#Kelsey")
		ActionOverride("J#Kelsey",ForceSpell("Jan",WIZARD_DISPEL_MAGIC_VISUALS_ONLY))
		ActionOverride("Jan",Wait(4))
		ActionOverride("Jan",SmallWait(8))
		ActionOverride("Jan",CreateVisualEffectObject("SPGFLSH1","Jan"))
		ActionOverride("Jan",PickUpItem("FWOats01"))
		ActionOverride("Jan",DestroyItem("FWOats01"))
		StartCutScene("FWct007")
END


